/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kevin
 */
public class Bienvenido extends javax.swing.JFrame  {
            private Usuario usuario;
            
    /**
     * Creates new form Bienvenido
     * @param usuario
     */
    public Bienvenido(Usuario usuario ){
        
        this.usuario = usuario;
        initComponents();
        labelUsuario.setText(this.usuario.getUsuario());
        apellidoUsuario.setText(this.usuario.getApellido());
        rolUsuario.setText(this.usuario.getRol());

        for(Equipo equipo:Login.equipos){
          for(Usuario user : equipo.getMiembro()){
              if(user.getUsuario().equals(this.usuario.getUsuario())){
                          equipoUsuario.setText(equipo.getNombre());
                          crear.setVisible(false);
                          modi.setVisible(false);
                                                      ver.setVisible(false);
                                                      eli.setVisible(false);
                                                      importar.setVisible(false);
                                                      llenarJTableM();

              }
                                    

          }
           if(equipo.getLider().getUsuario().equals(this.usuario.getUsuario())){
                            crear.setVisible(true);
                            modi.setVisible(true);
                            ver.setVisible(true);
                            verM.setVisible(false);
                                            equipoUsuario.setText("LIDER: "+equipo.getNombre());
  llenarJTableL();
              }
           
        }
                                    setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        verM = new javax.swing.JButton();
        importar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        apellidoUsuario = new javax.swing.JLabel();
        rolUsuario = new javax.swing.JLabel();
        equipoUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar5 = new javax.swing.JMenuBar();
        crear = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        modi = new javax.swing.JMenuItem();
        ver = new javax.swing.JMenuItem();
        eli = new javax.swing.JMenuItem();
        crearTarea = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 7, 70, -1));

        verM.setBackground(new java.awt.Color(204, 255, 204));
        verM.setForeground(new java.awt.Color(0, 0, 0));
        verM.setText("Cambiar estado de Tarea");
        verM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMActionPerformed(evt);
            }
        });
        getContentPane().add(verM, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 6, -1, -1));

        importar.setBackground(new java.awt.Color(204, 255, 204));
        importar.setForeground(new java.awt.Color(0, 0, 0));
        importar.setText("Importar Tareas");
        importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarActionPerformed(evt);
            }
        });
        getContentPane().add(importar, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 6, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("ROL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 90, -1));

        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 90, -1));

        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("APELLIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 90, -1));

        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("EQUIPO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 90, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, -1));

        labelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        labelUsuario.setText("jLabel2");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, -1));

        apellidoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        apellidoUsuario.setText("jLabel2");
        jPanel1.add(apellidoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, -1));

        rolUsuario.setBackground(new java.awt.Color(0, 0, 0));
        rolUsuario.setText("jLabel2");
        jPanel1.add(rolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 67, -1));

        equipoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        equipoUsuario.setText("No asignado");
        jPanel1.add(equipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 36, 192, 546));

        jTable1.setBackground(new java.awt.Color(153, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 360));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("TUS TAREAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 36, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/kevin/Escritorio/Proyecto/src/main/java/imagenes/plain-smooth-green-wall-texture.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 590));

        crear.setText("Proyecto");

        jMenuItem2.setText("Crear Proyecto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        crear.add(jMenuItem2);

        modi.setText("Modificar Proyecto");
        modi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modiActionPerformed(evt);
            }
        });
        crear.add(modi);

        ver.setText("Ver Proyectos");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        crear.add(ver);

        eli.setText("Eliminar Proyecto");
        eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliActionPerformed(evt);
            }
        });
        crear.add(eli);

        jMenuBar5.add(crear);

        crearTarea.setText("Tarea");

        jMenuItem6.setText("Crear Tareas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        crearTarea.add(jMenuItem6);

        jMenuItem7.setText("Ver tareas");
        crearTarea.add(jMenuItem7);

        jMenuItem8.setText(" Eliminar Tareas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        crearTarea.add(jMenuItem8);

        jMenuItem3.setText(" Modificar Tarea");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        crearTarea.add(jMenuItem3);

        jMenuBar5.add(crearTarea);

        setJMenuBar(jMenuBar5);

        pack();
    }// </editor-fold>//GEN-END:initComponents
                   private  void llenarJTableM(){
        
DefaultTableModel table = new DefaultTableModel(new String[]{"Us    uario asignado","NombreTarea", "Equipo", "Inicio", "Fin","Proyecto","Estado","estadoTareas","id"}, Login.tareas.size());

        jTable1.setModel(table);
        TableModel modelo = jTable1.getModel();
        for(int i = 0; i<Login.tareas.size();i++){
                       
                Tareas u = Login.tareas.get(i);
                 if(u.getMiembro().getUsuario().equals(this.usuario.getUsuario())){
                     
          
                                modelo.setValueAt(u.getMiembro().getUsuario(),i,0);
                  modelo.setValueAt(u.getNombreTarea(),i,1);
                         modelo.setValueAt(u.getEquipoAsignado().getNombre(),i,2);   
                      modelo.setValueAt(u.getFechaInicio(),i,3);
                modelo.setValueAt(u.getFechaFin(),i,4);
                                                                       
   modelo.setValueAt(u.getProyectoAsignado().getNombreProyecto(),i,5);
      modelo.setValueAt(u.getStatus(),i,6);
      modelo.setValueAt(u.getEstadoDeTareas(), i, 7);
            modelo.setValueAt(u.getId(),i,8);

                        }
                

        }
        }
    private  void llenarJTableL(){
        
DefaultTableModel table = new DefaultTableModel(new String[]{"Nombre","descripcion","fechaInicio","fechaFin","Equipo", "Usuario","Proyecto","Status","estadoTarea"}, Login.tareas.size());

        jTable1.setModel(table);
        TableModel modelo = jTable1.getModel();
        for(int i = 0; i<Login.tareas.size();i++){
   
                Tareas u = Login.tareas.get(i);
            if(u.getProyectoAsignado().getEquipoAsignado().getLider().getUsuario().equals(this.usuario.getUsuario())){     
                modelo.setValueAt(u.getNombreTarea(),i,0);
                modelo.setValueAt(u.getDescripcion(),i,1);
                      modelo.setValueAt(u.getFechaInicio(),i,2);
                modelo.setValueAt(u.getFechaFin(),i,3);
                
                                modelo.setValueAt(u.getEquipoAsignado().getNombre(),i,4);   
          
                                modelo.setValueAt(u.getMiembro().getUsuario(),i,5);
                                                              
   modelo.setValueAt(u.getProyectoAsignado().getNombreProyecto(),i,6);
      modelo.setValueAt(u.getStatus(),i,7);
      modelo.setValueAt(u.getEstadoDeTareas(), i, 8);
          }
           
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        // TODO add your handling code here:
            Log l = new Log();
           l.setVisible(true);
            this.dispose();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed
            JsonLectura json = new JsonLectura(usuario);
            json.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_importarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         CrearProyectoGerente gerente = new CrearProyectoGerente(usuario);
            gerente.setVisible(true);// TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void modiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiActionPerformed
               ModificarProyectoGerente modificar = new ModificarProyectoGerente(usuario);
                modificar.setVisible(true);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_modiActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
          VerProyectoGerente ver = new VerProyectoGerente(usuario);
                ver.setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed

    private void eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliActionPerformed
              EliminarProyecto eliminar = new EliminarProyecto(usuario);
                eliminar.setVisible(true);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_eliActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
           CrearTarea crear = new CrearTarea(usuario);
            crear.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void verMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMActionPerformed
        VerTareasMiembro verMi = new VerTareasMiembro(usuario);
        verMi.setVisible(true);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_verMActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        EliminarTarea eliminarTarea = new EliminarTarea(usuario);  
        eliminarTarea.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ModificarTarea modificarTarea = new ModificarTarea(usuario);
            modificarTarea.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoUsuario;
    private javax.swing.JMenu crear;
    private javax.swing.JMenu crearTarea;
    private javax.swing.JMenuItem eli;
    private javax.swing.JLabel equipoUsuario;
    private javax.swing.JButton importar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenuItem modi;
    private javax.swing.JLabel rolUsuario;
    private javax.swing.JMenuItem ver;
    private javax.swing.JButton verM;
    // End of variables declaration//GEN-END:variables
}
