/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author herma
 */
public class CrearTarea extends javax.swing.JFrame {
private Usuario usuario;
    /**
     * Creates new form CrearTarea
     */
    public CrearTarea(Usuario u) {
                    setLocationRelativeTo(null);

        initComponents();
        this.usuario=u;
System.out.println(this.usuario.getUsuario());
        for(Proyecto p : Login.proyectos){
         

            if(p.getEquipoAsignado().getLider().getUsuario().equals(this.usuario.getUsuario())){
            proyectosCombo.addItem(p.getNombreProyecto());
            break;
            }
            
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaInicioField = new javax.swing.JTextField();
        nombreTareaField = new javax.swing.JTextField();
        fechaFinField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        proyectosCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        miembroField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        descripcionField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        estadoTareaCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 46, -1, -1));

        jLabel2.setText("Fecha Inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 165, -1, -1));

        jLabel3.setText("Fecha Fin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 222, 68, -1));
        getContentPane().add(fechaInicioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 189, 78, -1));
        getContentPane().add(nombreTareaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 70, 81, -1));
        getContentPane().add(fechaFinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 249, 74, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("CREAR TAREA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 6, -1, -1));

        jLabel5.setText("Proyecto a asignar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 46, -1, -1));

        proyectosCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectosComboActionPerformed(evt);
            }
        });
        getContentPane().add(proyectosCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 97, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 50, 531, 253));

        jLabel6.setText("MIEMBROS DEL EQUIPO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel7.setText("Miembro a asignar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        miembroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miembroFieldActionPerformed(evt);
            }
        });
        getContentPane().add(miembroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 124, 82, -1));

        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 279, -1, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 192, 47, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("Solicitado");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 82, -1));

        jLabel9.setText("Descripcion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 100, -1, -1));
        getContentPane().add(descripcionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 124, 181, 59));

        jLabel10.setText(" EstadoTarea");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 252, -1, -1));

        estadoTareaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva" }));
        getContentPane().add(estadoTareaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 249, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void llenarTable(){
   
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           Tareas tarea = new Tareas();
        String nombreTarea = nombreTareaField.getText();
            String fechaInicio = fechaInicioField.getText();
            String fechaFin = fechaFinField.getText();
            String proyectoElegido = proyectosCombo.getSelectedItem().toString();
            String nombreMiembro = miembroField.getText();
           String descripcion = descripcionField.getText();
           String estadoTarea = estadoTareaCombo.getSelectedItem().toString();
            tarea.setNombreTarea(nombreTarea);
            tarea.setFechaInicio(fechaInicio);
            tarea.setFechaFin(fechaFin);
            tarea.setStatus("Solicitado");
            tarea.setDescripcion(descripcion);
            Proyecto pro =null;
     
            for(Proyecto p: Login.proyectos){
                if(proyectoElegido.equals(p.getNombreProyecto())){
                    pro=p; 
 
                System.out.println(pro.getEquipoAsignado().getMiembro());
                for(Usuario u:pro.getEquipoAsignado().getMiembro()){
                        if(nombreMiembro.equals(u.getUsuario())){
                    pro.asignarTarea(tarea);
                   tarea.setEquipoAsignado(pro.getEquipoAsignado());
                   tarea.setProyectoAsignado(pro);
                   tarea.setMiembro(u);
                   tarea.setId(Login.tareas.size());
                   tarea.setEstadoDeTareas(estadoTarea);
                    Login.tareas.add(tarea);
                   JOptionPane.showMessageDialog(this, "TAREA CREADA");

                }
                }   
            
                 }
            }
            
            
         
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void proyectosComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectosComboActionPerformed
           String proyectoElegido = proyectosCombo.getSelectedItem().toString(); 
        Equipo equi = null;          
        for(Proyecto p:Login.proyectos){
                    if(p.getNombreProyecto().equals(proyectoElegido)){
                            equi = p.getEquipoAsignado();
                                DefaultTableModel table = new DefaultTableModel(new String[]{"Nombre", "Apellido", "Correo", "Rol"}, equi.getMiembro().size());
    jTable1.setModel(table);
    TableModel modelo = jTable1.getModel();
    int row = 0;
    for (Usuario miembro : equi.getMiembro()) {
        modelo.setValueAt(miembro.getUsuario(), row, 0);
        modelo.setValueAt(miembro.getApellido(), row, 1);
        modelo.setValueAt(miembro.getCorreo(), row, 2);
        modelo.setValueAt(miembro.getRol(), row, 3);
        row++;
    }
                    }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_proyectosComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void miembroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miembroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miembroFieldActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcionField;
    private javax.swing.JComboBox<String> estadoTareaCombo;
    private javax.swing.JTextField fechaFinField;
    private javax.swing.JTextField fechaInicioField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField miembroField;
    private javax.swing.JTextField nombreTareaField;
    private javax.swing.JComboBox<String> proyectosCombo;
    // End of variables declaration//GEN-END:variables
}
