/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login;

import static com.mycompany.login.Login.equipos;
import static com.mycompany.login.Login.usuarios;
import java.awt.Label;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kevin
 */
public class CrearEquipo extends javax.swing.JFrame {
    private Usuario usuario;
    public int contador = 0;

    /**
     * Creates new form CrearEquipo
     * 
     * @param usuario
     */
    public CrearEquipo() {
         setLocationRelativeTo(null);
        initComponents();
        for (int i = 0; i < Login.usuarios.size(); i++) {
            Usuario u = Login.usuarios.get(i);

            if (u.getRol().equals("gerente")) {
                comboBox.addItem(u.getUsuario());

            }

        }
        //
        // for(Usuario persona: Login.usuarios){
        // combo.addItem(persona.getUsuario());
        // if(persona.getRol().equals("gerente")){
        //
        // }
        // }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipoField = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        equipoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoFieldActionPerformed(evt);
            }
        });

        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Asigne un lider");

        jLabel2.setText("Ingrese el nombre unico de equipo");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(equipoField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(equipoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxActionPerformed

        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
        // pantallaPrincipal principal = new pantallaPrincipal();
        // principal.
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        Equipo equipo = new Equipo();
        String nombreEquipo = equipoField.getText();

        equipo.setNombre(nombreEquipo);

        String nombreGerenteSeleccionado = comboBox.getSelectedItem().toString();

        Usuario lider = null;

        for (Usuario usuario : Login.usuarios) {
            if (usuario.getRol().equals("gerente") && usuario.getUsuario().equals(nombreGerenteSeleccionado)) {
                lider = usuario;
                break;
            }
        }
        if (lider != null) {
            boolean liderAsignado = false;
            for (Equipo e : Login.equipos) {
                if (e.getLider() != null && e.getLider().getUsuario().equals(nombreGerenteSeleccionado)) {
                    liderAsignado = true;
                    break;
                }
            }
            if (liderAsignado) {
                JOptionPane.showMessageDialog(this, "Este gerente ya ha sido asignado como líder de otro equipo.");
            } else {
                equipo.setLider(lider);
                equipo.setId(Login.equipos.size());
                Login.equipos.add(equipo);

                JOptionPane.showMessageDialog(this, "El equipo se ha agregado correctamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún gerente con el nombre seleccionado.");
        }

        // for (Equipo e : Login.equipos) {
        // System.out.println("Nombre del equipo: " + e.getNombre());
        // System.out.println("ID del equipo: " + e.getId());
        // if (e.getLider() != null) {
        // System.out.println("Líder del equipo: " + e.getLider().getUsuario());
        // } else {
        // System.out.println("El equipo no tiene líder asignado");
        // }
        // }

        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void equipoFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_equipoFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_equipoFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField equipoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
